server:
  port: 8083
spring:
  datasource:
    username: root
    password: 1030jie
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.73.140:3306/turing?characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSourceC3P0Adapter
  http:
    encoding:
      charset: UTF-8
  mvc:
    static-path-pattern: /resources/**
    view:
      prefix: /html/
      suffix: .html
    favicon:
      enabled: false
    resources:
      static-locations: /resources/
mybatis:
  type-aliases-package: com.turing.turing.entity
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  reasonable: true
  helper-dialect: mysql
logging:
  path: /var/log/
  file: turing-project.log