server:
  port: 8081
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/turing?characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
  http:
    encoding:
      force: true
      charset: UTF-8
  mvc:
    static-path-pattern: /resources/**
    view:
      prefix: /resources/
      suffix: .html
    favicon:
      enabled: false
  resources:
    static-locations: /resources/
mybatis:
  type-aliases-package: com.turing.turing.entity
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  reasonable: true
  helper-dialect: mysql